name: Check Broken Links in Markdown

on:
  push:
    branches:
      - main
      - master

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check links
      run: |
        find . -name "*.md" -exec grep -oP '\{%\s*embed\s*url="\K[^"]+' {} + | while read -r link; do
          echo "Checking link: $link"
          if wget --spider "$link" 2>&1 | grep -q '404 Not Found'; then
            echo "Link is broken: $link"
            # You can add your own logic here to handle or delete the file containing the broken link
          else
            echo "Link is reachable: $link"
          fi
        done
