name: Check Broken Links in Markdown

on:
  push:
    branches:
      - main
      - master

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check links
      run: |
        find . -name "*.md" -print0 | while IFS= read -r -d '' file; do
          grep -oP '\{%\s*embed\s*url="\K[^"]+' "$file" | while IFS= read -r link; do
            echo "Checking link: $link in file: $file"
            response_code=$(curl -s -o /dev/null -w "%{http_code}" "$link")
            if [ "$response_code" -ne 200 ]; then
              echo "Link is broken: $link in file: $file"
              # You can add your own logic here to handle or delete the file containing the broken link
            fi
          done
        done
