name: Check Broken Links in Markdown

on:
  push:
    branches:
      - main
      - master

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g markdown-link-check

    - name: Extract and check links
      run: |
        grep -rhoP --include='*.md' '{%\s*embed\s*url="\K[^"]*' . | \
          while IFS= read -r -d '' file; do \
            echo "Checking links in $file"; \
            cat "$file"; \
            markdown-link-check "$file" --config .markdown-link-check.json; \
          done > extracted-links.txt

    - name: Display extracted links
      run: cat extracted-links.txt
