name: Check Broken Links in Markdown

on:
  push:
    branches:
      - main
      - master

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g markdown-link-check

    - name: Extract and display links
      run: |
        find . -type f -name "*.md" -exec awk '/{%\s*embed\s*url="/{print substr($0, index($0,$3))}' {} + > extracted-links.txt
        cat extracted-links.txt

    - name: Check links with filenames
      run: |
        while IFS= read -r link; do
          filename=$(grep -rlF "$link" ./*.md)
          echo "Checking link in $filename: $link"
          markdown-link-check "$link" --config .markdown-link-check.json
        done < extracted-links.txt
